### ISSUE TITLE
How about a language field in the seri description ?

### ISSUE THREAD

**Issue by hreymond** [Lugrim/seri#23]
Since not everyone is comfortable about giving a talk of english, should we add a field to the `seri` language to define the language of a talk ? Similarly to the *speakers* attribute, the *lang* attribute would be useful only for talks.

Any opinion on this ?

**Comment by ororktn** [comment]
That's a great idea. I was also thinking about a "status" field to be able to have kind of "fixed" events (actual events) and "to be decided" events (drawn with something like dotted lines)
