### ISSUE TITLE
Bottom-right bound inherits month and year, but not top-left one

### ISSUE THREAD

**Issue by Docteur-Lalla** [Lugrim/seri#4]
When building the BoundingBox of events, it appears at [latex.rs:77](https://github.com/Lugrim/timetable-language/blob/674cdb7e7507b5f2aaa30f68d04bd0aba4665e36/src/passes/latex.rs#L77) that the bottom-right bound of the box inherits the month and year of the bottomest-rightest date, but the same operation does not happen when building the top-left bound at [latex.rs:66](https://github.com/Lugrim/timetable-language/blob/674cdb7e7507b5f2aaa30f68d04bd0aba4665e36/src/passes/latex.rs#L66).

Why is it like this? Is it normal?

**Comment by ororktn** [comment]
Hello,
Thanks for your issue. It isn't, that's an oversight, I was looking for a `with_date` function, maybe I shall implement it?

**Comment by Docteur-Lalla** [comment]
I'm working on some refactor of this code already, don't worry I'll change what is missing

**Comment by ororktn** [comment]
Fixed by #6
